export const metadata = {
  title: "Projects | Ukiyo Habitat",
  description: "Explore featured projects by Ukiyo Habitat, showcasing our expertise in sustainable and innovative architectural design.",
  keywords: [
    "Ukiyo Habitat projects",
    "landscape architecture projects India",
    "urban design case studies",
    "sustainable architecture projects",
    "ecological design portfolio",
    "public space design projects",
    "campus landscape projects",
    "water-sensitive design projects",
    "climate-responsive architecture",
    "adaptive reuse projects",
    "child-friendly space design",
    "urban resilience projects",
    "community placemaking case studies",
    "blue-green infrastructure projects",
    "sustainable urban development",
    "ecological restoration projects",
    "participatory design projects",
    "urban renewal projects India",
    "landscape-led masterplans",
    "environmental design portfolio",
    "social impact design projects",
    "Bandhavgarh landscape design",
    "Ahmedabad Haat Street",
    "Vastrapur Lake revitalization",
    "Kake Da Hotel design",
    "Chevella Mansion interior"
  ],
}; 